### ISSUE TITLE
sonarqube安装agent失败

### ISSUE THREAD

**Issue by exexute** [huoxianclub/LingZhi#5]
### 错误详情
JDK 11下启动sonarqube，安装agent后，出现sonarqube无法启动的情况，详情如下：
```
org.apache.catalina.LifecycleException: Failed to initialize component [Realm[Simple]]
	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:139)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:917)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:766)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:440)
	at org.sonar.server.app.EmbeddedTomcat.start(EmbeddedTomcat.java:65)
	at org.sonar.server.app.WebServer.start(WebServer.java:52)
	at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:97)
	at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:81)
	at org.sonar.server.app.WebServer.main(WebServer.java:99)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/apache/catalina/connector/Request.upgrade(Ljava/lang/Class;)Ljavax/servlet/http/HttpUpgradeHandler; @66: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[2]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @66
    flags: { }
    locals: { 'org/apache/catalina/connector/Request', 'java/lang/Class', top, 'org/apache/tomcat/InstanceManager', 'java/lang/Object' }
    stack: { uninitialized 60, uninitialized 60, 'java/lang/Object' }
```

### JDK版本
![image](https://user-images.githubusercontent.com/16431735/111936167-1b58d700-8b00-11eb-9a37-5ce71fd71ab6.png)

**Comment by exexute** [comment]
经测试，使用ASM 5.0版本的检测引擎可正常处理sonarqube的WEB应用；之前在某些环境下测试，ASM 5.0版本无法正确处理部分高版本的类，因此，换用ASM高版本来解决该问题，但，高版本在部分环境中无法有效检测；因此，重新整理JDK与ASM的兼容问题，梳理出正确的解决方案

**Comment by coffeehb** [comment]
目前用着有点懵逼。。
 
- 一是，记不住搜索语法，在http://aws.iast.huoxian.cn:8000/taint/search不知道如何下手。
- 二是，在Web端看不到任何数据，会怀疑hook是不是没有生效。
- 三是，扫描策略 修改了，怎么知道是不是已经下发成功，agent是否生效
